platform :ios, '8.0'

def shared_pods
	pod 'LHToolbar', '1.3.0-beta'
    pod 'OTAcceleratorPackUtil', '~> 2.0.0-beta2'
    pod 'OTScreenShareKit', '~> 2.0.0-beta1'
end

target 'OTAnnotationKit' do
    shared_pods
end

target 'OTAnnotationKitTests' do
  shared_pods
  pod 'Kiwi'
end
