platform :ios, '8.0'

def shared_pods
	pod 'LHToolbar', '1.3.0-beta'
    pod 'OTAcceleratorPackUtil'
    pod 'OTScreenShareKit'
end

target 'OTAnnotationAccPackKit' do 
	shared_pods
end

target 'OTAnnotationKit' do
    shared_pods
end

target 'OTAnnotationKitStatic' do
    shared_pods
end

target 'OTAnnotationKitTests' do
  shared_pods
  pod 'Kiwi'
end
